apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"argotest","app.kubernetes.io/managed-by":"terraform","app.kubernetes.io/name":"api","app.kubernetes.io/part-of":"api","app.kubernetes.io/version":"82e6b5d"},"managedFields":[{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:labels":{".":{},"f:app.kubernetes.io/managed-by":{},"f:app.kubernetes.io/name":{},"f:app.kubernetes.io/part-of":{},"f:app.kubernetes.io/version":{}}},"f:spec":{"f:ports":{".":{},"k:{\"port\":80,\"protocol\":\"TCP\"}":{".":{},"f:port":{},"f:protocol":{},"f:targetPort":{}}},"f:selector":{".":{},"f:app":{}},"f:sessionAffinity":{},"f:type":{}}},"manager":"HashiCorp","operation":"Update","time":"2021-06-10T06:41:01Z"},{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}},"f:labels":{"f:app.kubernetes.io/instance":{}}}},"manager":"argocd-application-controller","operation":"Update","time":"2021-07-01T18:37:48Z"}],"name":"evercast-api","namespace":"evercast-dev","resourceVersion":"12883642","selfLink":"/api/v1/namespaces/evercast-dev/services/evercast-api","uid":"66e4bd15-0ebe-4e45-b22d-b8c257bdd6a5"},"spec":{"clusterIP":"172.20.55.169","ports":[{"port":80,"protocol":"TCP","targetPort":3000}],"selector":{"app":"evercast-api"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2021-07-01T20:25:27Z"
  labels:
    app.kubernetes.io/instance: argotest
    app.kubernetes.io/managed-by: terraform
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: api
    app.kubernetes.io/version: 82e6b5d
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/part-of: {}
          f:app.kubernetes.io/version: {}
      f:spec:
        f:clusterIP: {}
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: argocd-application-controller
    operation: Update
    time: "2021-07-01T20:25:26Z"
  name: evercast-api
  namespace: evercast-dev
  resourceVersion: "12930362"
  selfLink: /api/v1/namespaces/evercast-dev/services/evercast-api
  uid: 73ac7d7a-6aac-44f5-9ae1-db323902e6e0
spec:
  clusterIP: 172.20.55.169
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: evercast-api
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
